alias pmv='/teamspace/studios/this_studio/autogrow4new/mgltools_x86_64Linux2_1.5.6/bin/pmv'
alias adt='/teamspace/studios/this_studio/autogrow4new/mgltools_x86_64Linux2_1.5.6/bin/adt'
alias vision='/teamspace/studios/this_studio/autogrow4new/mgltools_x86_64Linux2_1.5.6/bin/vision'
alias cadd='/teamspace/studios/this_studio/autogrow4new/mgltools_x86_64Linux2_1.5.6/bin/cadd'
alias pythonsh='/teamspace/studios/this_studio/autogrow4new/mgltools_x86_64Linux2_1.5.6/bin/pythonsh'
